name: Rust

on:
  push:
    branches: [ master, staging ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose --release --all --target x86_64-unknown-linux-gnu
    - name: Run tests
      run: cargo test --verbose --release --all --target x86_64-unknown-linux-gnu
    - uses: actions/upload-artifact@v4
      with:
        name: eris-x86_64-unknown-linux-gnu
        path: target/x86_64-unknown-linux-gnu/release/eris
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose --release --all --target x86_64-pc-windows-msvc
    - name: Run tests
      run: cargo test --verbose --release --all --target x86_64-pc-windows-msvc
    - uses: actions/upload-artifact@v4
      with:
        name: eris-x86_64-pc-windows-msvc
        path: target/x86_64-pc-windows-msvc/release/eris
