name: Rust

on:
  push:
    branches: [ master, staging ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            exe-suffix: ''
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            exe-suffix: .exe
    name: 'Build: ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose --release --all --target ${{ matrix.target }}
    - name: Run tests
      run: cargo test --verbose --release --all --target ${{ matrix.target }}
    - uses: actions/upload-artifact@v4
      with:
        name: eris-${{ matrix.target }}
        path: ${{ github.workspace }}/target/${{ matrix.target }}/release/eris${{ matrix.exe-suffix }}
