name: Rust

on:
  push:
    branches: [ master, staging ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
    - uses: Swatinem/rust-cache@v1
    - name: Check that there is a single Tokio version used
      run: cargo metadata --format-version 1 | jq '.packages[] | select(.name == "tokio") | .version' | wc -l | grep -q '^1$'
    - name: Build
      run: cargo build --verbose --release --all --target x86_64-unknown-linux-gnu
    - name: Run tests
      run: cargo test --verbose --release --all --target x86_64-unknown-linux-gnu
    - uses: actions/upload-artifact@v2
      with:
        name: eris-x86_64-unknown-linux-gnu
        path: target/x86_64-unknown-linux-gnu/release/eris
