name: Rust

on:
  push:
    branches: [master, staging]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            exe-suffix: ""
            cargo-extra-args: ""
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            exe-suffix: .exe
            cargo-extra-args: "--no-default-features"
    name: "Build: ${{ matrix.target }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - uses: Swatinem/rust-cache@v2
      - name: Install dependencies (Linux)
        run: sudo apt-get install -y libleptonica-dev libtesseract-dev
        if: runner.os == 'Linux'
      - name: Build
        run: cargo build --verbose --release --all --target ${{ matrix.target }} ${{ matrix.cargo-extra-args }}
      - name: Run tests
        run: cargo test --verbose --release --all --target ${{ matrix.target }} ${{ matrix.cargo-extra-args }}
      - uses: actions/upload-artifact@v7
        with:
          name: eris-${{ matrix.target }}
          path: ${{ github.workspace }}/target/${{ matrix.target }}/release/eris${{ matrix.exe-suffix }}
